openapi: 3.0.3
info:
  title: Contenidos - OpenAPI 3.0
  version: 1.0.1
servers:
- url: /
tags:
- name: Peliculas
  description: Todo sobre tu pelicula
- name: Series
  description: Todo sobre tu serie
- name: Temporadas
  description: Todo sobre la temporada
- name: Capitulos
  description: Todo sobre el capitulo
- name: Actores
  description: Todo sobre el actor
- name: Directores
  description: Todo sobre el director
paths:
  /series:
    get:
      tags:
      - Series
      summary: Obtener todas las series
      operationId: series_get
      responses:
        "200":
          description: Lista de series
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.series_controller
  /series/{id}:
    get:
      tags:
      - Series
      summary: Obtener una serie por ID
      operationId: series_id_get
      parameters:
      - name: id
        in: path
        description: ID de la serie a buscar
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Información de la serie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Serie'
        "404":
          description: Serie no encontrada
      x-openapi-router-controller: swagger_server.controllers.series_controller
  /series/titulo/{titulo}:
    get:
      tags:
      - Series
      summary: Obtener una serie por Nombre
      operationId: series_titulo_titulo_get
      parameters:
      - name: titulo
        in: path
        description: Serie con el nombre a buscar
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Información de la series con ese titulo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
                x-content-type: application/json
        "404":
          description: Serie no encontrada
      x-openapi-router-controller: swagger_server.controllers.series_controller
  /series/genero/{genero}:
    get:
      tags:
      - Series
      summary: Obtener una serie por genero
      operationId: series_genero_genero_get
      parameters:
      - name: genero
        in: path
        description: Series con el genero a buscar
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Información de la serie de ese genero
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Serie'
                x-content-type: application/json
        "404":
          description: Serie no encontrada
      x-openapi-router-controller: swagger_server.controllers.series_controller
  /peliculas:
    get:
      tags:
      - Peliculas
      summary: Obtener todas las películas
      operationId: peliculas_get
      responses:
        "200":
          description: Lista de películas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pelicula'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.peliculas_controller
  /peliculas/{id}:
    get:
      tags:
      - Peliculas
      summary: Obtener una pelicula por id
      operationId: peliculas_id_get
      parameters:
      - name: id
        in: path
        description: ID de la pelicula a buscar
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Información de la pelicula
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pelicula'
        "404":
          description: Pelicula no encontrada
      x-openapi-router-controller: swagger_server.controllers.peliculas_controller
  /peliculas/titulo/{titulo}:
    get:
      tags:
      - Peliculas
      summary: Obtener todas las películas que contengan el título
      operationId: peliculas_titulo_titulo_get
      parameters:
      - name: titulo
        in: path
        description: Título parcial de la película a buscar
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de películas que contienen el título especificado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pelicula'
                x-content-type: application/json
        "404":
          description: No se encontraron películas que coincidan con el título proporcionado
      x-openapi-router-controller: swagger_server.controllers.peliculas_controller
  /peliculas/genero/{genero}:
    get:
      tags:
      - Peliculas
      summary: Obtener todas las películas
      operationId: peliculas_genero_genero_get
      parameters:
      - name: genero
        in: path
        description: ID de la pelicula a buscar
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de películas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pelicula'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.peliculas_controller
  /peliculas/{id}/actores:
    get:
      tags:
      - Peliculas
      summary: Obtener los actores de una película específica
      operationId: peliculas_id_actores_get
      parameters:
      - name: id
        in: path
        description: ID de la película
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de actores que participan en la película
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'
                x-content-type: application/json
        "404":
          description: No se encontraron actores para la película proporcionada
      x-openapi-router-controller: swagger_server.controllers.peliculas_controller
  /peliculas/{id}/directores:
    get:
      tags:
      - Peliculas
      summary: Obtener los directores de una película específica
      operationId: peliculas_id_directores_get
      parameters:
      - name: id
        in: path
        description: ID de la película
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de directores que participaron en la película
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Director'
                x-content-type: application/json
        "404":
          description: No se encontraron directores para la película proporcionada
      x-openapi-router-controller: swagger_server.controllers.peliculas_controller
  /series/{id}/temporadas:
    get:
      tags:
      - Temporadas
      summary: Obtener todas las temporadas de una serie
      operationId: series_id_temporadas_get
      parameters:
      - name: id
        in: path
        description: ID de la serie
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de temporadas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Temporada'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.temporadas_controller
  /series/{id}/temporadas/{temporadaId}/capitulos:
    get:
      tags:
      - Capitulos
      summary: Obtener todos los capítulos de una temporada específica
      operationId: series_id_temporadas_temporada_id_capitulos_get
      parameters:
      - name: id
        in: path
        description: ID de la serie
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: temporadaId
        in: path
        description: ID de la temporada
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de capítulos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Capitulo'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.capitulos_controller
  /series/{id}/actores:
    get:
      tags:
      - Series
      summary: Obtener actores de una serie específica
      operationId: series_id_actores_get
      parameters:
      - name: id
        in: path
        description: ID de la serie
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de actores que participan en la serie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'
                x-content-type: application/json
        "404":
          description: No se encontraron actores para la serie proporcionada
      x-openapi-router-controller: swagger_server.controllers.series_controller
  /series/{id}/directores:
    get:
      tags:
      - Series
      summary: Obtener los directores de una serie específica
      operationId: series_id_directores_get
      parameters:
      - name: id
        in: path
        description: ID de la serie
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Lista de directores que participan en la serie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Director'
                x-content-type: application/json
        "404":
          description: No se encontraron directores para la serie proporcionada
      x-openapi-router-controller: swagger_server.controllers.series_controller
  /actores:
    get:
      tags:
      - Actores
      summary: Obtener todos los actores
      operationId: actores_get
      responses:
        "200":
          description: Lista de actores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.actores_controller
  /actores/{id}:
    get:
      tags:
      - Actores
      summary: Obtener actor por id
      operationId: actores_id_get
      parameters:
      - name: id
        in: path
        description: Actor Correspondiente a ese id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Actor Correspondiente a ese id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Actor'
      x-openapi-router-controller: swagger_server.controllers.actores_controller
  /directores:
    get:
      tags:
      - Directores
      summary: Obtener todos los directores
      operationId: directores_get
      responses:
        "200":
          description: Lista de directores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Director'
                x-content-type: application/json
        "404":
          description: No se encontraron directores
      x-openapi-router-controller: swagger_server.controllers.directores_controller
  /directores/{id}:
    get:
      tags:
      - Directores
      summary: Obtener director por id
      operationId: directores_id_get
      parameters:
      - name: id
        in: path
        description: Director por ID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Director Por id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Director'
      x-openapi-router-controller: swagger_server.controllers.directores_controller
components:
  schemas:
    Serie:
      type: object
      properties:
        id:
          type: string
        titulo:
          type: string
        genero:
          type: string
        descripcion:
          type: string
        actores:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
        temporadas:
          type: array
          items:
            $ref: '#/components/schemas/Temporada'
        capitulos:
          type: array
          items:
            $ref: '#/components/schemas/Capitulo'
      example:
        descripcion: descripcion
        actores:
        - fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
          id: id
          nombre: nombre
        - fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
          id: id
          nombre: nombre
        capitulos:
        - null
        - null
        temporadas:
        - descripcion: descripcion
          capitulos:
          - descripcion: descripcion
            numCapitulo: 6
            director:
              fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
              id: id
              nombre: nombre
            titulo: titulo
            duracion: duracion
            id: id
          - descripcion: descripcion
            numCapitulo: 6
            director:
              fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
              id: id
              nombre: nombre
            titulo: titulo
            duracion: duracion
            id: id
          numero: 0
          id: id
        - descripcion: descripcion
          capitulos:
          - descripcion: descripcion
            numCapitulo: 6
            director:
              fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
              id: id
              nombre: nombre
            titulo: titulo
            duracion: duracion
            id: id
          - descripcion: descripcion
            numCapitulo: 6
            director:
              fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
              id: id
              nombre: nombre
            titulo: titulo
            duracion: duracion
            id: id
          numero: 0
          id: id
        genero: genero
        titulo: titulo
        id: id
    Pelicula:
      type: object
      properties:
        id:
          type: string
        titulo:
          type: string
        genero:
          type: string
        descripcion:
          type: string
        director:
          $ref: '#/components/schemas/Director'
        actores:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
        duracion:
          type: string
          format: time
      example:
        descripcion: descripcion
        actores:
        - fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
          id: id
          nombre: nombre
        - fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
          id: id
          nombre: nombre
        director:
          fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
          id: id
          nombre: nombre
        genero: genero
        titulo: titulo
        duracion: duracion
        id: id
    Actor:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        fecha_nacimiento:
          type: string
          format: date-time
      example:
        fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
        id: id
        nombre: nombre
    Director:
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        fecha_nacimiento:
          type: string
          format: date-time
      example:
        fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
        id: id
        nombre: nombre
    Temporada:
      type: object
      properties:
        id:
          type: string
        descripcion:
          type: string
        numero:
          type: integer
        capitulos:
          type: array
          items:
            $ref: '#/components/schemas/Capitulo'
      example:
        descripcion: descripcion
        capitulos:
        - descripcion: descripcion
          numCapitulo: 6
          director:
            fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
            id: id
            nombre: nombre
          titulo: titulo
          duracion: duracion
          id: id
        - descripcion: descripcion
          numCapitulo: 6
          director:
            fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
            id: id
            nombre: nombre
          titulo: titulo
          duracion: duracion
          id: id
        numero: 0
        id: id
    Capitulo:
      type: object
      properties:
        id:
          type: string
        titulo:
          type: string
        numCapitulo:
          type: integer
        descripcion:
          type: string
        duracion:
          type: string
          format: time
        director:
          $ref: '#/components/schemas/Director'
      example:
        descripcion: descripcion
        numCapitulo: 6
        director:
          fecha_nacimiento: 2000-01-23T04:56:07.000+00:00
          id: id
          nombre: nombre
        titulo: titulo
        duracion: duracion
        id: id

